FROM ubuntu:22.04

RUN apt-get update && apt-get -y install python3 python3-pip libcairo2-dev pkg-config python3-dev git htop build-essential tesseract-ocr ffmpeg libsm6 libxext6 poppler-utils

# SET TIMEZONE TO AVOID ANSWERING PROMPTS
RUN ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN echo Etc/UTC > /etc/timezone

WORKDIR /preprocess-api
COPY requirements_upload.txt .

RUN pip install -r requirements_upload.txt

COPY upload_app.py .env version.md .
COPY utils utils/
COPY preprocessors preprocessors/

EXPOSE 8082
CMD ["uvicorn", "upload_app:app", "--host", "0.0.0.0", "--port", "8082"]
